// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"Synrec_Pause","status":true,"description":"v1.0 Pause the game when on map (When menu disabled and pause switch on)","parameters":{"Pause Switch":"1","Pause Graphics":"[\"{\\\"Image\\\":\\\"pause\\\",\\\"Rotation\\\":\\\"0\\\",\\\"Anchor X\\\":\\\"0\\\",\\\"Anchor Y\\\":\\\"0\\\",\\\"Position X\\\":\\\"0\\\",\\\"Position Y\\\":\\\"0\\\",\\\"Scroll X\\\":\\\"0\\\",\\\"Scroll Y\\\":\\\"0\\\"}\"]","Pause BGM":"{}"}}
];
